### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by gitihobo** [GeekyGhost/multidiffusionLazyRiffusionRegionPrompting#1]
Is this an automatic1111 extension or how do you use it?

**Comment by GeekyGhost** [comment]
> Is this an automatic1111 extension or how do you use it?

It's a stand alone python script. You just run it, but like it's internet code man. So always check out the code even if it's someone you trust. GPT can probably even help make some improvements, but it just creates the json file for the extension in Automatic1111

**Comment by GeekyGhost** [comment]
> Is this an automatic1111 extension or how do you use it?

The multidiffusion extension was written by someone else, I'm just lazy and wanted a way to short cut the regions for testing 😅. This was my solution.
